# Generated by Django 4.2 on 2025-12-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='notion_url',
            field=models.URLField(blank=True, help_text='Notion darsliklariga havola', max_length=500, null=True, verbose_name='Notion URL'),
        ),
    ]
